% Thresholding of grayscale images
%
%431-400 Year Long Project, LA1 - Medical Image Processing 2003
% Supervisor     :  Dr Lachlan Andrew
% Group Members  :  Alister Fong    78629   a.fong1@ugrad.unimelb.edu.au
%                   Lee Siew Teng   102519  s.lee1@ugrad.unimelb.edu.au
%                   Loh Jien Mei    103650  j.loh1@ugrad.unimelb.edu.au
%
% threshold.m, threshold.fig (Run this!!)
%       Displays the scales of an image and displays the output of 
%       threshold_grayscale_image.m
% threshold_grayscale_image.m 
%       Thresholds an image given the desired values. If the value 
%       of the pixel is within the desired range, it is set to 
%       white (255) otherwise it remains black (0)
